### ISSUE TITLE
Versions of `python` and `python-dev`, etc. don't necessarily match

### ISSUE THREAD

**Issue by OrangeDog** [cdalvaro/docker-salt-master#154]
```
python${PYTHON_VERSION} python3-dev libpython3-dev
```

You're only specifying the minor version for `python`, and not any of the related packages. They will instead use the default for the distribution, ignoring `PYTHON_VERSION`.

You either need to specify the same version for all of them (and use e.g. the deadsnakes repo), or not bother with `PYTHON_VERSION` and use the distro default for everything.

**Comment by cdalvaro** [comment]
I've been hesitating this for a while and you are right. I think that best thing is to remove any reference to `PYTHON_VERSION` and use the distro default.

**Comment by OrangeDog** [comment]
You could also consider using one of the python images as a base, to get non-default pythons (but not pre-release debians).

e.g. `python:3.10-slim-bullseye`

**Comment by cdalvaro** [comment]
> You could also consider using one of the python images as a base, to get non-default pythons (but not pre-release debians).
> 
> e.g. `python:3.10-slim-bullseye`

I tried it, but I got an error with the salt-bootstrap script.

**Comment by cdalvaro** [comment]
Thank you for reporting this issue, @OrangeDog!
