### ISSUE TITLE
Container doesn't start

### ISSUE THREAD

**Issue by bensteinberg** [cdalvaro/docker-salt-master#245]
**Describe the bug**
The `salt_master` container doesn't start, because of a permissions error:

    chown: changing ownership of '/home/salt/data/keys/master.pem': Permission denied

**To Reproduce**

On an M1 Mac, I ran

    wget https://raw.githubusercontent.com/cdalvaro/docker-salt-master/master/docker-compose.yml
    docker compose up

**Expected behavior**
I expected the `salt_master` container to be running.

**Additional info**
```
% docker compose up
[+] Running 2/0
 ✔ Network saltdocker_default  Created                                                                                  0.0s
 ✔ Container salt_master       Created                                                                                  0.0s
Attaching to salt_master
salt_master  | [INFO] - Mapping UID and GID for salt:salt to 1000:1000 ...
salt_master  | [INFO] - Configuring directories ...
salt_master  | '/srv' -> '/home/salt/data/srv'
salt_master  | '/var/log/salt' -> '/home/salt/data/logs/salt'
salt_master  | [INFO] - Configuring logrotate ...
salt_master  | [INFO] - Configuring container timezone ...
salt_master  | [INFO] - Setting TimeZone -> Etc/UTC ...
salt_master  | [INFO] - Configuring salt-master service ...
salt_master  | [INFO] - Setting up salt keys ...
salt_master  | [INFO] -  ==> Setting up salt-master keys ...
salt_master  | [INFO] -      Creating new keys ...
salt_master  | [INFO] -  ==> Setting up GPG keys ...
salt_master  | [INFO] -      Could not find GPG keys. GPG setup skipped.
salt_master  | [INFO] - Setting up salt keys permissions ...
salt_master  | chmod: changing permissions of '/home/salt/data/keys/master.pem': Permission denied
salt_master exited with code 1
salt_master  | chown: changing ownership of '/home/salt/data/keys/master.pem': Permission denied
salt_master  | chown: changing ownership of '/home/salt/data/keys/master.pem': Permission denied
salt_master  | chown: changing ownership of '/home/salt/data/keys/master.pem': Permission denied
...
```

**Version report (please complete the following information):**

- Host OS: Darwin myhostname 23.5.0 Darwin Kernel Version 23.5.0: Wed May  1 20:12:58 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6000 arm64
- Docker: Docker version 26.1.1, build 4cf5afa
- Image tag: `3007.1`

**Additional context**
This is the same as #226, I think. Let me know if I should have put this report in that issue.

I've experimented with changing `PUID` and `PGID` to my local uid and gid, but there's no difference.

**Comment by cdalvaro** [comment]
Thank you for opening this issue @bensteinberg, I'll try to fix it asap.

**Comment by bensteinberg** [comment]
Thanks, @cdalvaro! I'll try it out. I'm hoping to store/manage the keys on the host. I'll let you know how it goes.

**Comment by cdalvaro** [comment]
> Thanks, @cdalvaro! I'll try it out. I'm hoping to store/manage the keys on the host. I'll let you know how it goes.

Great! Thank you for your help!

**Comment by cdalvaro** [comment]
Hi @bensteinberg! I've made some changes to the permissions management that fix your issue.

Could you try this image before I merge #248?

```
ghcr.io/cdalvaro/docker-salt-master:development
```

**Comment by bensteinberg** [comment]
> Hi @bensteinberg! I've made some changes to the permissions management that fix your issue.
> 
> Could you try this image before I merge #248?
> 
> ```
> ghcr.io/cdalvaro/docker-salt-master:development
> ```

Sorry for the delay -- thanks for doing this. I'll check it out.
