### ISSUE TITLE
Salt Project needs to migrate the Salt package repository

### ISSUE THREAD

**Issue by mjlabe** [cdalvaro/docker-salt-master#273]
**Is your feature request related to a problem? Please describe.**

Salt Project has also needed to migrate the Salt package repository:

repo.saltproject.io -> packages.broadcom.com: A public Artifactory endpoint for package repository hosting (rpm/deb/windows/etc.)

All self-hosted CI/CD runners, connected to our GitHub/GitLab repositories, will become non-functional when our public cloud backend is decommissioned.

https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

**Describe the solution you'd like**
Update cloud backend for new Broadcom repositories.

**Describe alternatives you've considered**
N/A

**Additional context**
https://saltproject.io/blog/salt-project-package-repo-migration-and-guidance/

**Comment by cdalvaro** [comment]
Hi @mjlabe! Thank you for opening this issue!

It is already in my TODO list 😉

**Comment by mjlabe** [comment]
Thank you and thank you for the project!

**Comment by cdalvaro** [comment]
> Thank you and thank you for the project!

Thank you for using it!
